// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRVaRGg32SY0LoDKQLGA4vbLPhZfk_50',
    appId: '1:797794385996:web:c3ed2560e706478babb4e9',
    messagingSenderId: '797794385996',
    projectId: 'wathiq-ac6e2',
    authDomain: 'wathiq-ac6e2.firebaseapp.com',
    storageBucket: 'wathiq-ac6e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BrPF5GRLKhCi1FyG7hRsa19nP_NqBPg',
    appId: '1:797794385996:android:c9e63a7389821e74abb4e9',
    messagingSenderId: '797794385996',
    projectId: 'wathiq-ac6e2',
    storageBucket: 'wathiq-ac6e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqEi7jKBGXg1llzgx6Lv9mw3KMGS-5RFU',
    appId: '1:797794385996:ios:1f113f22a9acb04aabb4e9',
    messagingSenderId: '797794385996',
    projectId: 'wathiq-ac6e2',
    storageBucket: 'wathiq-ac6e2.appspot.com',
    iosClientId: '797794385996-hd57057g93nt2nmltpudbabl8ed8gteg.apps.googleusercontent.com',
    iosBundleId: 'com.example.wathiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqEi7jKBGXg1llzgx6Lv9mw3KMGS-5RFU',
    appId: '1:797794385996:ios:1f113f22a9acb04aabb4e9',
    messagingSenderId: '797794385996',
    projectId: 'wathiq-ac6e2',
    storageBucket: 'wathiq-ac6e2.appspot.com',
    iosClientId: '797794385996-hd57057g93nt2nmltpudbabl8ed8gteg.apps.googleusercontent.com',
    iosBundleId: 'com.example.wathiq',
  );
}
